[package]
name = "state-validator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-utils = { path = "../gw-utils" }
gw-state = { path = "../gw-state" }
ckb-smt = { path = "../ckb-smt" }
