[package]
name = "gw-types"
version = "1.12.2"
authors = ["Nervos Network"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = ["molecule/std", "ckb-fixed-hash", "ckb-types"]
deprecated = []

[dependencies]
molecule = { version = "0.7.3", default-features = false }
cfg-if = "1"
gw-hash = { path = "../hash", default-features = false }
ckb-fixed-hash = { version = "0.105.1", optional = true }
ckb-types = { version = "0.105.1", default-features = false, optional = true }
primitive-types = { version = "0.12", default-features = false, features = [ "impl-serde", "impl-rlp" ] }

[build-dependencies]
molecule-codegen = "0.7.3"
