#ifndef GW_ERRORS_H_
#define GW_ERRORS_H_

/* Errors */
#define GW_ERROR_NOT_FOUND 42
#define GW_ERROR_INVALID_DATA 43
#define GW_ERROR_INSUFFICIENT_CAPACITY 44
#define GW_ERROR_INVALID_CONTEXT 45
#define GW_ERROR_DYNAMIC_LINKING 46
#define GW_ERROR_MISMATCH_CHANGE_SET 47
#define GW_ERROR_MISMATCH_RETURN_DATA 48
#define GW_ERROR_UNKNOWN_ARGS 49
/* Merkle Errors*/
#define GW_ERROR_INVALID_PROOF_LENGTH 60
#define GW_ERROR_INVALID_PROOF 61
#define GW_ERROR_INVALID_STACK 62
#define GW_ERROR_INVALID_SIBLING 63

#endif
