[package]
name = "gw-hash"
version = "1.12.0-rc2"
authors = ["Nervos Network"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2b-ref = { version = "0.3.1", default-features = false }
