version = "0.7.0"
deployment = "deployment.toml"
[rust]
workspace_dir = "contracts"
toolchain = "nightly-2022-08-01"
docker_image = "thewawar/ckb-capsule:2022-08-01"

[[contracts]]
name = "state-validator"
template_type = "Rust"

[[contracts]]
name = "deposit-lock"
template_type = "Rust"

[[contracts]]
name = "custodian-lock"
template_type = "Rust"

[[contracts]]
name = "withdrawal-lock"
template_type = "Rust"

[[contracts]]
name = "challenge-lock"
template_type = "Rust"

[[contracts]]
name = "stake-lock"
template_type = "Rust"

[[contracts]]
name = "always-success"
template_type = "Rust"

[[contracts]]
name = "eth-account-lock"
template_type = "Rust"
