[package]
name = "polyjuice-tests"
version = "1.5.0"
authors = ["Linfeng Qian <thewawar@gmail.com>"]
edition = "2018"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
gw-types     = { path = "../../crates/types/" }
gw-common    = { path = "../../crates/common/" }
gw-db        = { path = "../../crates/db/" }
gw-store     = { path = "../../crates/store/" }
gw-utils     = { path = "../../crates/utils/" }
gw-config    = { path = "../../crates/config/" }
gw-traits    = { path = "../../crates/traits/" }
gw-generator = { path = "../../crates/generator/" }

####
#Sync patch version with godwoken core.
tracing = { version = "0.1.36", features = ["attributes"] } 
ckb-vm = { version = "=0.22.0", default-features = false }
ckb-vm-aot = { version = "=0.22.0" }
####

lazy_static = "1.4"
tiny-keccak = "1.4"
rlp = "0.5.0"
hex = "0.4.2"
env_logger = "0.9"
anyhow = "1.0"

# ethabi = "^17.0.0"
# rand = "0.7.3"
# blake2b-rs = "0.2"

[dev-dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
ethabi = "18.0.0"

