[package]
name = "gw-syscall-simulator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-common    = { path = "../../../../gwos/crates/common/" }
gw-types     = { path = "../../../../gwos/crates/types/" }
gw-generator = { path = "../../../../crates/generator/" }
gw-smt       = { path = "../../../../crates/smt/" }
gw-store     = { path = "../../../../crates/store/" }
gw-utils     = { path = "../../../../crates/utils/" }
gw-config    = { path = "../../../../crates/config/", features = ["no-builtin"] }
gw-traits    = { path = "../../../../crates/traits/" }
once_cell = "1.14.0"
anyhow = "1.0"
hex = "0.4"
