[package]
name = "gw-rpc-ws-server"
version = "0.1.0"
authors = ["Nervos network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-types = "0.100.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_plain = "0.3.0"
jsonrpc-core = "18.0"
jsonrpc-derive = "18.0"
jsonrpc-ws-server = "18.0"
jsonrpc-server-utils = "18.0"
jsonrpc-pubsub = "18.0"
log = "0.4.14"
anyhow = "1.0"
lazy_static = "1.4"
gw-runtime = { path = "../runtime" }
gw-jsonrpc-types = { path = "../jsonrpc-types" }
gw-types = { path = "../types" }
futures = "0.3"
async-channel = "1.4"
