[package]
name = "gw-utils"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.10.0"
gw-types  = { path = "../../crates/types", default-features = false }
gw-common  = { path = "../../crates/common", default-features = false }
