name: unit_tests_ubuntu
concurrency:
  group: unit_tests_ubuntu-${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust components
      run: rustup component add rustfmt && rustup component add clippy
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
    - name: Install moleculec v0.7.2
      run: CARGO_TARGET_DIR=target/ cargo install moleculec --version 0.7.2
    - name: Check format
      run: cargo fmt -- --check
    - name: Cargo clippy check
      run: cargo clippy
    - name: Copy contracts from prebuild docker images
      run: devtools/fetch-binaries.sh
    - name: Tests
      run: cargo test --all-targets
