name: Web3 Indexer Docker Build Push

on:
  push:
    branches: ["develop", '*-rc*']
    paths:
      - 'web3/**'
    # todo: how do we release tag under monorepo?
    tags: ["web3@v*.*.*"]
  workflow_dispatch:

env:
  # Use ghcr.io only 
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: godwoken-web3-indexer-prebuilds

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web3

    # If you specify the access for any of these scopes, all of those that are not specified are set to none.
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      # GitHub automatically creates a unique GITHUB_TOKEN secret to use in this workflow. 
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      - name: Get Current Commit Id
        id: commit
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: New Commit Build => Build and push commit image to ${{ env.REGISTRY }}
        if: ${{ github.ref_type != 'tag' }}
        uses: docker/build-push-action@v2
        with:
          file: web3/docker/indexer/Dockerfile
          context: ./web3
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}-${{ steps.commit.outputs.sha_short }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # extract web3 tags from the special format: web3@v*.*.*
      - name: Split web3 tags
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        env:
          metatags: ${{ steps.meta.outputs.tags }}
        id: split
        run: echo "::set-output name=tags::${metatags/web3@/}"

      # Build and push Docker image with Buildx (don't push on PR)
      # only for new tag
      - name: Official Release Build => Build and push tag image to ${{ env.REGISTRY }}
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        uses: docker/build-push-action@v2
        with:
          file: web3/docker/indexer/Dockerfile
          context: ./web3
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.split.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

